env:
  browser: true
  node: true
  commonjs: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
plugins:
  - 'react'
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  allowImportExportEverywhere: true
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: 0
  react/prop-types:
    - 2
    -
      ignore:
        - children

#  [<enabled>, { ignore: <ignore>, customValidators: <customValidator> }]